fix(lpeg): Removing static build of lpeg
nix-community/neovim-nightly-overlay pull request #683
Opened 2024-10-25 22:58 UTC by hurricanehrndz

These  fixes should be contributed and fixed back to nixpkg master.

2024-10-25 23:12 UTC, GaetanLepage commented
> These fixes should be contributed and fixed back to nixpkg master.

What I don't understand is that this logic seems to be present on the upstream derivation of neovim.

2024-10-25 23:24 UTC, hurricanehrndz commented
Not all, read closely

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Gaétan Lepage ***@***.***>
Sent: Friday, October 25, 2024 5:12:25 PM
To: nix-community/neovim-nightly-overlay ***@***.***>
Cc: Carlos Hernandez ***@***.***>; Author ***@***.***>
Subject: Re: [nix-community/neovim-nightly-overlay] fix(lpeg): Removing static build of lpeg (PR #683)


These fixes should be contributed and fixed back to nixpkg master.

What I don't understand is that this logic seems to be present on the upstream derivation of neovim.

—
Reply to this email directly, view it on GitHub<https://github.com/nix-community/neovim-nightly-overlay/pull/683#issuecomment-2439028203>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABMJBTJHELTX73LFRPSEFGLZ5LF5TAVCNFSM6AAAAABQUFBMQSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMZZGAZDQMRQGM>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-10-25 23:54 UTC, willruggiano requested changes

2024-10-25 23:54 UTC, willruggiano commented on flake/packages/neovim.nix
> +      myNeovimLuaEnv = pkgs.luajit.withPackages requiredLuaPkgs;
Looks good. One nit: remove this and just inline it below.

2024-10-26 00:00 UTC, willruggiano commented on flake/packages/neovim.nix
> +      myNeovimLuaEnv = pkgs.luajit.withPackages requiredLuaPkgs;
jk i got u

2024-10-26 08:45 UTC, GaetanLepage commented
> These fixes should be contributed and fixed back to nixpkg master.

Can this be done today or should we delay it until nvim 0.11 lands on master ?

2024-10-26 10:32 UTC, GaetanLepage requested changes
Ok I see ! Thanks for taking the time to fix it.
I will try to upstream it if possible/

2024-10-26 10:32 UTC, GaetanLepage commented on flake/packages/neovim.nix
> +              cat makefile
```suggestion
```

2024-11-02 23:52 UTC, GaetanLepage commented
As this patch [ended up being upstream](https://github.com/NixOS/nixpkgs/pull/351423), I will close this PR.
Thank you for submitting it in the first place !

2024-11-02 23:52 UTC, closed without merging